Создать карточку GPS сенсора #99
M4MController/frontend pull request #114
Opened 2019-04-27 23:50 UTC by JohnKeats97

Просто лютые костыли, которые нужно переделать, а то это какой-то пиздец. Но оно работает, только зум он при каждом обновлении данных так же обновляет на дефолтный, а не на тот что ты выставил, короч нужно туда какой-то state подключить, обработчики навешивать, чтобы норм было, но в целом, если не зумить, то оно само карту по координатам подстаивает. Ну и сделать нормальный курсор, а не кружочек. Показывать норм, оно работает, но нужно переделать.

2019-04-27 23:59 UTC, JohnKeats97 commented
GOOGLE_API_MAPS_KEY = ключ (скинул в телеге), и еще package-lock.json кажись надо убрать.

2019-04-28 10:05 UTC, ed-asriyan requested changes

2019-04-28 10:05 UTC, ed-asriyan commented on app/styles/component-styles/sensor-gps-card.scss
> +}
сделай размеры кратными `$grid-step`, пожалуйста

2019-04-28 10:05 UTC, ed-asriyan commented on app/templates/components/sensor-gps-card.hbs
> +{{/g-map}}
и тут перевод строки в конце файла заодно, иначе литер жалуется

2019-04-28 10:32 UTC, ed-asriyan commented on app/templates/components/sensor-gps-card.hbs
> +{{#g-map lat=sensor.value.lat lng=sensor.value.lon zoom=12 zoomControl=true styles=primaryMapStyle as |g|}}
Можно попробовать zoom к переменной привязать. Может быть поможет

2019-04-28 10:36 UTC, JohnKeats97 commented on app/templates/components/sensor-gps-card.hbs
> +{{#g-map lat=sensor.value.lat lng=sensor.value.lon zoom=12 zoomControl=true styles=primaryMapStyle as |g|}}
Тут надо зум к стэйту какому-то привязать, но я сейчас не могу это сделать, я думаю пока норм, но я потом сделаю

2019-04-28 10:38 UTC, ed-asriyan commented on app/templates/components/sensor-gps-card.hbs
> +{{#g-map lat=sensor.value.lat lng=sensor.value.lon zoom=12 zoomControl=true styles=primaryMapStyle as |g|}}
Ок

2019-04-28 10:42 UTC, JohnKeats97 commented
Там еще нужно сделать увеличение курсора, о том где ты, в зависимости от зума, короч много че там надо сделать, обраточиков навешать как раз на все.

2019-04-28 12:18 UTC, ed-asriyan approved these changes

2019-04-29 11:25 UTC, merged